### ISSUE TITLE
Missing or Invalid Plugins

### ISSUE THREAD

**Issue by pikachurus** [mantisbt-plugins/faq#11]
mantisbt 2.26.0
php-fpm 7.4
nginx 1.24
mysql 8.0

unziped in plugins folder

![image](https://github.com/mantisbt-plugins/faq/assets/16227309/1fda0109-2365-4ca1-87b4-1ac8258278be)

**Comment by CasN** [comment]
Please rename the plugin directory to: FAQ

**Comment by pikachurus** [comment]
![image](https://github.com/mantisbt-plugins/faq/assets/16227309/263e800c-b726-42b6-a62b-f8b6e8499465)

thanks! now it's ok!
