### ISSUE TITLE
APPLICATION WARNING #300  ----- plugin_faq_plugin_format_title

### ISSUE THREAD

**Issue by ozaneermis** [mantisbt-plugins/faq#12]
![300](https://github.com/mantisbt-plugins/faq/assets/74829981/5c2fc70f-8261-4726-858f-344fe52d7ece)
![1](https://github.com/mantisbt-plugins/faq/assets/74829981/c605cdf9-1d52-4d96-bfad-32b0e0f67a02)
I checked the database, i have a table which is mantis_plugin_faq_results_table

**Comment by CasN** [comment]
Can you please ensure that the plugin is installed in the FAQ directory (so all with capitals) and see if the issue is still there?

**Comment by ozaneermis** [comment]
I tried. It didn't work, but I found another solution. When I tried to install as 'FAQ', Mantis warned me about upgrading the FAQ plugin and gave me an error. Before trying to install as 'faq', I deleted the mantis_bug_faq_results_table in the database and changed all the text in scripts_english.txt from 'FAQ' to 'faq'. It worked.

**Comment by CasN** [comment]
Good to hear you solved it!
