### ISSUE TITLE
Could you add any free editor

### ISSUE THREAD

**Issue by ZakharchukEduard** [mantisbt-plugins/faq#13]
Hi.
You plugin is very much needed and helpful to me.
Thank you very much for your work.
The only thing I am missing is a WYSIWYG editor.
Could you add any free editor (CKEditor, TyniMCE, etc.) to edit FAQ with the ability to switch between Markdown and HTML editing?
Once again thank you very much for your work.

**Comment by CasN** [comment]
Check the following plugin, this may be usefull for you: https://github.com/mantisbt-plugins/VEditor
