### ISSUE TITLE
Replace occurences of deprecated `db_query` API

### ISSUE THREAD

**Issue by dregad** [mantisbt-plugins/faq#2]
In MantisBT 1.3, the `db_query()` function will be removed from the API (see mantisbt/mantisbt#128).
The following occurences have been found in this plugin; they should be replaced
by `db_query_bound()` calls

```
FAQ/pages/faq_api.php:43:       return db_query( $query );
FAQ/pages/faq_api.php:53:       return db_query( $query );
FAQ/pages/faq_api.php:69:       return db_query( $query );
FAQ/pages/faq_api.php:79:       $result = db_query( $query );
FAQ/pages/faq_api.php:90:       $result = db_query( $query );
FAQ/pages/faq_menu_page.php:63:$result = db_query( $query );
FAQ/pages/faq_view_page.php:17: $result = db_query( $query );

```

**Comment by Kirill** [comment]
@dregad Can you check this commit https://github.com/Kirill/faq/commit/862429d78d597c5426121e7b47460cce0c09ff31 ? I right understand?

**Comment by dregad** [comment]
Yes this is the idea.

Please note that in 2.x, the API changes again (*db_query_bound()* gets deprecated and becomes an alias for *db_query()*)

**Comment by CasN** [comment]
All deprecated functions have been removed
