### ISSUE TITLE
Please update for Mantis 2.5

### ISSUE THREAD

**Issue by digitalsigi** [mantisbt-plugins/faq#6]
Hi,
I would like to use the plugin with mantis 2.5, could you pls update?
Thx

**Comment by TonyGravagno** [comment]
What doesn't work?

**Comment by digitalsigi** [comment]
Hi Tony,
actually I even can't install it. The plugin has Mantisbt core 1.2.0 as prereq, but I am running 2.10.
I look like the API has changed between 1.2 and 2.x; but I don't have the knowledge to do the port.
Josef

**Comment by ydentidad** [comment]
Almost nothing, since the nucleus of antis 1 changes with respect to 2, and there are functions that no longer use the most frequent format. The way to add the menu is different.

**Comment by Kirill** [comment]
This plugin only for MantisBT 1.x.x. Please look author of plugin and ask about new version.
